In [3]:
import pandas as pd

In [139]:
lend = pd.read_excel("/Users/shans/Downloads/Lending_data.xlsx")

C:\Users\shans\anaconda3\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [140]:
lend.head()

,Name of Lending Institution,HQ State,Rank,TA Ratio1,TBL Ratio1,"Amount ($1,000)",Number,Lender Asset Size,"Amount ($1,000).1",Number .1,Unnamed: 10,"Amount ($1,000).2",Number .2,CC Amount/TA1
0,NaN,NaN,-1,-2,-3,-4,-5,-6,-7.0,-8.0,NaN,-9.0,-10.0,-11
1,American Express Co.,NY,1,0.23829,0.999544,16350038,3603226,>$50B,16318089.0,3603088.0,NaN,31949.0,138.0,0.28
2,First Citizens Banchares,NC,2,0.187393,0.49083,3914507,117702,$10B-$50B,378394.0,105081.0,NaN,3536113.0,12621.0,.
3,Wintrust Financial Corp.,IL,3,0.168999,0.383561,2842793,136801,$10B-$50B,800526.0,126455.0,NaN,2042267.0,10346.0,0
4,Zions Bancorp,UT,4,0.117973,0.260577,6231770,52612,>$50B,526206.0,32973.0,NaN,5705564.0,19639.0,0

In [141]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  96 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         94 non-null     object
 3   TA Ratio1                    94 non-null     object
 4   TBL Ratio1                   94 non-null     object
 5   Amount ($1,000)              94 non-null     object
 6   Number                       94 non-null     object
 7   Lender Asset Size            94 non-null     object
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Unnamed: 10                  0 non-null      float64
 11  Amount ($1,000).2            94 non-null     float64
 12  Number .2                    94 non-null     float64
 13  CC Amount/TA1                94 non-null     object
dtypes: float64(5), object(9)
memory usage: 10.7+ KB

In [142]:
lend.shape

(97, 14)

In [ ]:
# dropping all the null values

In [143]:
lend.isnull()

,Name of Lending Institution,HQ State,Rank,TA Ratio1,TBL Ratio1,"Amount ($1,000)",Number,Lender Asset Size,"Amount ($1,000).1",Number .1,Unnamed: 10,"Amount ($1,000).2",Number .2,CC Amount/TA1
0,True,True,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,False,False,False,False,False,False,False,False,False,False,True,False,False,False
93,False,False,False,False,False,False,False,False,False,False,True,False,False,False
94,False,True,True,True,True,True,True,True,True,True,True,True,True,True
95,False,True,True,True,True,True,True,True,True,True,True,True,True,True
96,False,True,True,True,True,True,True,True,True,True,True,True,True,True

In [12]:
lend.isnull().sum()

Name of Lending Institution     1
HQ State                        4
Rank                            3
TA Ratio1                       3
TBL Ratio1                      3
Amount ($1,000)                 3
Number                          3
Lender Asset Size               3
Amount ($1,000).1               3
Number .1                       3
Unnamed: 10                    97
Amount ($1,000).2               3
Number .2                       3
CC Amount/TA1                   3
dtype: int64

In [144]:
lend_1=lend.copy()

In [145]:
lend_1= lend.drop(columns=['Unnamed: 10'])

In [146]:
lend_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  96 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         94 non-null     object
 3   TA Ratio1                    94 non-null     object
 4   TBL Ratio1                   94 non-null     object
 5   Amount ($1,000)              94 non-null     object
 6   Number                       94 non-null     object
 7   Lender Asset Size            94 non-null     object
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     object
dtypes: float64(4), object(9)
memory usage: 10.0+ KB

In [149]:
del lend['Unnamed: 10']

In [150]:
lend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  96 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         94 non-null     object
 3   TA Ratio1                    94 non-null     object
 4   TBL Ratio1                   94 non-null     object
 5   Amount ($1,000)              94 non-null     object
 6   Number                       94 non-null     object
 7   Lender Asset Size            94 non-null     object
 8   Amount ($1,000).1            94 non-null     float64
 9   Number .1                    94 non-null     float64
 10  Amount ($1,000).2            94 non-null     float64
 11  Number .2                    94 non-null     float64
 12  CC Amount/TA1                94 non-null     object
dtypes: float64(4), object(9)
memory usage: 10.0+ KB

In [151]:
lend.isnull().sum()

Name of Lending Institution    1
HQ State                       4
Rank                           3
TA Ratio1                      3
TBL Ratio1                     3
Amount ($1,000)                3
Number                         3
Lender Asset Size              3
Amount ($1,000).1              3
Number .1                      3
Amount ($1,000).2              3
Number .2                      3
CC Amount/TA1                  3
dtype: int64

In [152]:
lend.head()

,Name of Lending Institution,HQ State,Rank,TA Ratio1,TBL Ratio1,"Amount ($1,000)",Number,Lender Asset Size,"Amount ($1,000).1",Number .1,"Amount ($1,000).2",Number .2,CC Amount/TA1
0,NaN,NaN,-1,-2,-3,-4,-5,-6,-7.0,-8.0,-9.0,-10.0,-11
1,American Express Co.,NY,1,0.23829,0.999544,16350038,3603226,>$50B,16318089.0,3603088.0,31949.0,138.0,0.28
2,First Citizens Banchares,NC,2,0.187393,0.49083,3914507,117702,$10B-$50B,378394.0,105081.0,3536113.0,12621.0,.
3,Wintrust Financial Corp.,IL,3,0.168999,0.383561,2842793,136801,$10B-$50B,800526.0,126455.0,2042267.0,10346.0,0
4,Zions Bancorp,UT,4,0.117973,0.260577,6231770,52612,>$50B,526206.0,32973.0,5705564.0,19639.0,0

In [21]:
lend.tail()

,Name of Lending Institution,HQ State,Rank,TA Ratio1,TBL Ratio1,"Amount ($1,000)",Number,Lender Asset Size,"Amount ($1,000).1",Number .1,"Amount ($1,000).2",Number .2,CC Amount/TA1
92,Charles Schwab Bk,NV,NR,-,-,-,-,>$10B,0.0,0.0,0.0,0.0,.
93,Third FS&LA,OH,NR,-,-,-,-,>$10B,0.0,0.0,0.0,0.0,.
94,"*The bank was formerly known as GE Money Bank,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,1 TA = total domestic assets held by the lende...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,"Source: U.S. Small Business Administration, Of...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [153]:
lend_bkp=lend.dropna()

In [154]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     object
 3   TA Ratio1                    93 non-null     object
 4   TBL Ratio1                   93 non-null     object
 5   Amount ($1,000)              93 non-null     object
 6   Number                       93 non-null     object
 7   Lender Asset Size            93 non-null     object
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     object
dtypes: float64(4), object(9)
memory usage: 10.2+ KB

In [155]:
lend_bkp.isnull().sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      0
TBL Ratio1                     0
Amount ($1,000)                0
Number                         0
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [ ]:
#no null values ..cleaned

In [ ]:
#Replace the '-' value with the column mean

In [156]:
(lend_bkp=='-').sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      4
TBL Ratio1                     5
Amount ($1,000)                4
Number                         4
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [157]:
d=(lend_bkp=='-').sum()
d

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      4
TBL Ratio1                     5
Amount ($1,000)                4
Number                         4
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [158]:
lend_bkp['TA Ratio1'].value_counts()

TA Ratio1
-           4
0.012968    1
0.011237    1
0.019009    1
0.031035    1
           ..
0.046765    1
0.036391    1
0.028649    1
0.048534    1
0.023015    1
Name: count, Length: 90, dtype: int64

In [159]:
import numpy as np

In [ ]:
 #to replace mean values we have to convert them as null.then using fillna we can replace mean values..as - it consider string dt

In [160]:
lend_bkp=lend_bkp.replace('-',np.nan)

C:\Users\shans\AppData\Local\Temp\ipykernel_31728\58654558.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lend_bkp=lend_bkp.replace('-',np.nan)

In [161]:
lend_bkp['TA Ratio1'].value_counts()

TA Ratio1
0.238290    1
0.023015    1
0.011237    1
0.019009    1
0.031035    1
           ..
0.046765    1
0.036391    1
0.028649    1
0.048534    1
0.000000    1
Name: count, Length: 89, dtype: int64

In [162]:
lend_bkp.isnull().sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      4
TBL Ratio1                     5
Amount ($1,000)                4
Number                         4
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [163]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     object
 3   TA Ratio1                    89 non-null     float64
 4   TBL Ratio1                   88 non-null     float64
 5   Amount ($1,000)              89 non-null     float64
 6   Number                       89 non-null     float64
 7   Lender Asset Size            93 non-null     object
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     object
dtypes: float64(8), object(5)
memory usage: 10.2+ KB

In [34]:
lend_bkp.mean()

TypeError: Could not convert ['American Express Co. First Citizens BancharesWintrust Financial Corp.Zions BancorpSynovus Financial Corp.BB&T Corp. FNB Corp. Capital One Financial Corp.Fulton Financial Corp. Regions Financial Corp.U S Bancorp.First Niagara Financial Grp. Lauritzen Corp. Huntington Bancshares Inc.Bancorpsouth Inc.TCF Financial CorpGE Capital Retail Bk*                 JPMorgan Chase & Co Citigroup Popular Hancock Holding CompanyM&T Bk Corp Bank of Amer Corp Central Bancompany Arvest Bk Grp. Compass Bk Wells Fargo & Co PNC Financial Svc. Group Bank of The West BMO Harris Bank NAUmpqua HCT D Bk NACullen/Frost Bkr First Horizon Nat Corp. Commerce Bancshares Suntrust Bk Susquehanna BancsharesAssociated Banc Corp. Fifth Third BancorpKeycorp Prosperity BancsharesFirstmerit Corp. Valley Nat BancorpWebster Financial Corp. Peoples United Bk             RBS Citizens NA Sovereign Bk NADiscover Financial ServicesEast W BancorpComerica Ally Financial Iberiabank Corp. Firstbank Holding CompanyBarclays Bk DE Rabobank NA UMB Financial CorpCathay Gen. BancorpGE Capital Bk                     International Bshrs Corp. Signature Bk                  BOK Financial CorpFirst Bancorp Union Bk NA BankUnited Bank of HI Corp. State Farm Bk FSB         HSBC Bk USA NAWashington Fed.                Scottrade Bk                  Astoria FS & LA               Hudson City Svg Bk FSB        Svb Financial Grp. UBS Bk USACity Nat Corp. Privatebancorp Northern Trust Corp. USAA FSB                  Investors Bancorp MHCNew York Cmnty BC First Republic Bk             Everbank                      New York Private B&TR Corp. Morgan Stanley Bk NA Flagstar Bk FSB               Onewest Bk FSB              Bank of NY Mellon Corp. Goldman Sachs Group The Deutsche Bk Tc Americas USAA Svg. Bank                   State Street Corp. E Trade Bk                    Charles Schwab Bk             Third FS&LA                   '] to numeric

In [164]:
lend_bkp.select_dtypes(include='number')

,TA Ratio1,TBL Ratio1,"Amount ($1,000)",Number,"Amount ($1,000).1",Number .1,"Amount ($1,000).2",Number .2
1,0.238290,0.999544,16350038.0,3603226.0,16318089.0,3603088.0,31949.0,138.0
2,0.187393,0.490830,3914507.0,117702.0,378394.0,105081.0,3536113.0,12621.0
3,0.168999,0.383561,2842793.0,136801.0,800526.0,126455.0,2042267.0,10346.0
4,0.117973,0.260577,6231770.0,52612.0,526206.0,32973.0,5705564.0,19639.0
5,0.162333,0.381387,4227168.0,22675.0,539666.0,9593.0,3687502.0,13082.0
...,...,...,...,...,...,...,...,...
89,0.000000,NaN,0.0,1.0,0.0,1.0,0.0,0.0
90,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
91,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
92,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
93,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [65]:
lend_bkp.select_dtypes(include='number').mean()

TA Ratio1            4.866798e-02
TBL Ratio1           2.511965e-01
Amount ($1,000)      3.184791e+06
Number               2.164190e+05
Amount ($1,000).1    1.002631e+06
Number .1            1.985947e+05
Amount ($1,000).2    2.045180e+06
Number .2            8.515957e+03
dtype: float64

In [165]:
lend_bkp.fillna(lend_bkp.select_dtypes(include='number').mean())

,Name of Lending Institution,HQ State,Rank,TA Ratio1,TBL Ratio1,"Amount ($1,000)",Number,Lender Asset Size,"Amount ($1,000).1",Number .1,"Amount ($1,000).2",Number .2,CC Amount/TA1
1,American Express Co.,NY,1,0.238290,0.999544,1.635004e+07,3.603226e+06,>$50B,16318089.0,3603088.0,31949.0,138.0,0.28
2,First Citizens Banchares,NC,2,0.187393,0.490830,3.914507e+06,1.177020e+05,$10B-$50B,378394.0,105081.0,3536113.0,12621.0,.
3,Wintrust Financial Corp.,IL,3,0.168999,0.383561,2.842793e+06,1.368010e+05,$10B-$50B,800526.0,126455.0,2042267.0,10346.0,0
4,Zions Bancorp,UT,4,0.117973,0.260577,6.231770e+06,5.261200e+04,>$50B,526206.0,32973.0,5705564.0,19639.0,0
5,Synovus Financial Corp.,GA,5,0.162333,0.381387,4.227168e+06,2.267500e+04,$10B-$50B,539666.0,9593.0,3687502.0,13082.0,0.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,USAA Svg. Bank,NV,NR,0.000000,0.251196,0.000000e+00,1.000000e+00,>$10B,0.0,1.0,0.0,0.0,.
90,State Street Corp.,MA,NR,0.048668,0.251196,3.184791e+06,2.164190e+05,>$50B,0.0,0.0,0.0,0.0,0
91,E Trade Bk,VA,NR,0.048668,0.251196,3.184791e+06,2.164190e+05,>$10B,0.0,0.0,0.0,0.0,.
92,Charles Schwab Bk,NV,NR,0.048668,0.251196,3.184791e+06,2.164190e+05,>$10B,0.0,0.0,0.0,0.0,.
93,Third FS&LA,OH,NR,0.048668,0.251196,3.184791e+06,2.164190e+05,>$10B,0.0,0.0,0.0,0.0,.

In [166]:
lend_bkp.isnull().sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      4
TBL Ratio1                     5
Amount ($1,000)                4
Number                         4
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [167]:
lend_bkp.fillna(lend_bkp.select_dtypes(include='number').mean(),inplace=True)

In [168]:
lend_bkp.isnull().sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      0
TBL Ratio1                     0
Amount ($1,000)                0
Number                         0
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [169]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     object
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     object
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     object
dtypes: float64(8), object(5)
memory usage: 10.2+ KB

In [42]:
#3. Encode Lender asset size into 0,1,2

In [170]:
lend_bkp['Lender Asset Size']

1     >$50B
2     $10B-$50B
3     $10B-$50B
4     >$50B
5     $10B-$50B
              ...
89    >$10B
90    >$50B
91    >$10B
92    >$10B
93    >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [171]:
lend_bkp['Lender Asset Size'].value_counts()

Lender Asset Size
$10B-$50B               43
>$50B                   32
>$10B                   18
Name: count, dtype: int64

In [172]:
lend_bkp['Lender Asset Size'].replace('$10B-$50B',0)

1     >$50B
2     $10B-$50B
3     $10B-$50B
4     >$50B
5     $10B-$50B
              ...
89    >$10B
90    >$50B
91    >$10B
92    >$10B
93    >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [173]:
lend_bkp['Lender Asset Size']=lend_bkp['Lender Asset Size'].replace('$10B-$50B',0)

In [174]:
lend_bkp['Lender Asset Size'].value_counts()

Lender Asset Size
$10B-$50B               43
>$50B                   32
>$10B                   18
Name: count, dtype: int64

In [175]:
lend_bkp['Lender Asset Size']

1     >$50B
2     $10B-$50B
3     $10B-$50B
4     >$50B
5     $10B-$50B
              ...
89    >$10B
90    >$50B
91    >$10B
92    >$10B
93    >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [176]:
lend_bkp['Lender Asset Size'].replace(['$10B-$50B','>$50B','>$10B'],[0,1,2])

1     >$50B
2     $10B-$50B
3     $10B-$50B
4     >$50B
5     $10B-$50B
              ...
89    >$10B
90    >$50B
91    >$10B
92    >$10B
93    >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [177]:
lend_bkp['Lender Asset Size'].unique()

array(['>$50B               ', '$10B-$50B           ',
       '>$10B               '], dtype=object)

In [178]:
lend_bkp['Lender Asset Size']=lend_bkp['Lender Asset Size'].str.strip()

In [179]:
lend_bkp['Lender Asset Size'].unique()

array(['>$50B', '$10B-$50B', '>$10B'], dtype=object)

In [180]:
lend_bkp['Lender Asset Size'].replace('$10B-$50B',0)

1     >$50B
2         0
3         0
4     >$50B
5         0
      ...
89    >$10B
90    >$50B
91    >$10B
92    >$10B
93    >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [181]:
lend_bkp['Lender Asset Size'].replace('>$50B',1)

1             1
2     $10B-$50B
3     $10B-$50B
4             1
5     $10B-$50B
        ...
89        >$10B
90            1
91        >$10B
92        >$10B
93        >$10B
Name: Lender Asset Size, Length: 93, dtype: object

In [182]:
lend_bkp['Lender Asset Size'].replace(['$10B-$50B','>$50B','>$10B'],[0,1,2])

C:\Users\shans\AppData\Local\Temp\ipykernel_31728\2231355978.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lend_bkp['Lender Asset Size'].replace(['$10B-$50B','>$50B','>$10B'],[0,1,2])

1     1
2     0
3     0
4     1
5     0
     ..
89    2
90    1
91    2
92    2
93    2
Name: Lender Asset Size, Length: 93, dtype: int64

In [183]:
lend_bkp['Lender Asset Size']=lend_bkp['Lender Asset Size'].replace(['$10B-$50B','>$50B','>$10B'],[0,1,2])

C:\Users\shans\AppData\Local\Temp\ipykernel_31728\3683172730.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lend_bkp['Lender Asset Size']=lend_bkp['Lender Asset Size'].replace(['$10B-$50B','>$50B','>$10B'],[0,1,2])

In [184]:
lend_bkp['Lender Asset Size'].value_counts()

Lender Asset Size
0    43
1    32
2    18
Name: count, dtype: int64

In [186]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     object
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     int64
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     object
dtypes: float64(8), int64(1), object(4)
memory usage: 10.2+ KB

In [97]:
#############4. Replace '.' with column mean

In [187]:
(lend_bkp=='.').sum()

Name of Lending Institution    0
HQ State                       0
Rank                           0
TA Ratio1                      0
TBL Ratio1                     0
Amount ($1,000)                0
Number                         0
Lender Asset Size              0
Amount ($1,000).1              0
Number .1                      0
Amount ($1,000).2              0
Number .2                      0
CC Amount/TA1                  0
dtype: int64

In [188]:
(lend_bkp == '.').any() #check column wise

Name of Lending Institution    False
HQ State                       False
Rank                           False
TA Ratio1                      False
TBL Ratio1                     False
Amount ($1,000)                False
Number                         False
Lender Asset Size              False
Amount ($1,000).1              False
Number .1                      False
Amount ($1,000).2              False
Number .2                      False
CC Amount/TA1                  False
dtype: bool

In [189]:
(lend_bkp == '.').any().any() #checks is there at least one  in entire df

np.False_

In [190]:
(lend_bkp == '.').values.any()

np.False_

In [191]:
lend_bkp.iloc[:,6:].value_counts()

Number        Lender Asset Size  Amount ($1,000).1  Number .1  Amount ($1,000).2  Number .2  CC Amount/TA1
2.164190e+05  2                  0.0                0.0        0.0                0.0            .            3
2.644700e+04  0                  112694.0           26443.0    1666.0             4.0            .            1
5.615100e+04  1                  1087373.0          37405.0    4473118.0          18746.0    0                1
5.261200e+04  1                  526206.0           32973.0    5705564.0          19639.0    0                1
4.688700e+04  1                  424404.0           33066.0    3425035.0          13821.0    0                1
                                                                                                             ..
4.552000e+03  0                  56126.0            2222.0     627927.0           2330.0         .            1
4.390000e+03  0                  76018.0            2165.0     883874.0           2225.0     0                1
4.230000e+03  0                  63952.0            2522.0     414686.0           1708.0         .            1
3.820000e+03  0                  62413.0            3112.0     193639.0           708.0      0                1
3.603226e+06  1                  16318089.0         3603088.0  31949.0            138.0      0.28             1
Name: count, Length: 91, dtype: int64

In [192]:
lend_bkp['CC Amount/TA1'].value_counts()

CC Amount/TA1
    .      47
0          30
0.01        7
0.03        2
0.28        1
0.25        1
0.05        1
0.06        1
0.1         1
0.07        1
0.02        1
Name: count, dtype: int64

In [193]:
lend_bkp['CC Amount/TA1'].unique()

array([0.28, '    .  ', 0, 0.01, 0.25, 0.05, 0.06, 0.1, 0.03, 0.07, 0.02],
      dtype=object)

In [194]:
lend_bkp['CC Amount/TA1'].str.strip()

1     NaN
2       .
3     NaN
4     NaN
5     NaN
     ...
89      .
90    NaN
91      .
92      .
93      .
Name: CC Amount/TA1, Length: 93, dtype: object

In [196]:
lend_bkp['CC Amount/TA1'].dtype

dtype('O')

In [197]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     object
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     int64
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     object
dtypes: float64(8), int64(1), object(4)
memory usage: 10.2+ KB

In [201]:
pd.to_numeric(lend_bkp['CC Amount/TA1'], errors='coerce').unique()

array([0.28,  nan, 0.  , 0.01, 0.25, 0.05, 0.06, 0.1 , 0.03, 0.07, 0.02])

In [202]:
lend_bkp['CC Amount/TA1'].unique()

array([0.28, '    .  ', 0, 0.01, 0.25, 0.05, 0.06, 0.1, 0.03, 0.07, 0.02],
      dtype=object)

In [203]:
lend_bkp['CC Amount/TA1']=pd.to_numeric(lend_bkp['CC Amount/TA1'], errors='coerce')

In [204]:
lend_bkp['CC Amount/TA1'].unique()

array([0.28,  nan, 0.  , 0.01, 0.25, 0.05, 0.06, 0.1 , 0.03, 0.07, 0.02])

In [206]:
lend_bkp['CC Amount/TA1'].replace(np.nan,lend_bkp['CC Amount/TA1'].mean()).unique()

array([0.28      , 0.02086957, 0.        , 0.01      , 0.25      ,
       0.05      , 0.06      , 0.1       , 0.03      , 0.07      ,
       0.02      ])

In [207]:

lend_bkp['CC Amount/TA1']=lend_bkp['CC Amount/TA1'].replace(np.nan,lend_bkp['CC Amount/TA1'].mean())

In [209]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     object
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     int64
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     float64
dtypes: float64(9), int64(1), object(3)
memory usage: 10.2+ KB

In [ ]:
##5. Replace Rank Column ‘NR’ Values with ‘0’ Rank

In [211]:
lend_bkp['Rank'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 15, 16, 17, 18, 19, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 'NR'], dtype=object)

In [213]:
lend_bkp['Rank'].replace('NR',0).unique()

C:\Users\shans\AppData\Local\Temp\ipykernel_31728\3253108803.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lend_bkp['Rank'].replace('NR',0).unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 16, 17, 18, 19, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,  0])

In [215]:
lend_bkp['Rank'].replace('NR',0).unique().dtype

C:\Users\shans\AppData\Local\Temp\ipykernel_31728\697828637.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lend_bkp['Rank'].replace('NR',0).unique().dtype

dtype('int64')

In [216]:
lend_bkp['Rank']=lend_bkp['Rank'].replace('NR',0)

C:\Users\shans\AppData\Local\Temp\ipykernel_31728\2817700544.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lend_bkp['Rank']=lend_bkp['Rank'].replace('NR',0)

In [217]:
lend_bkp['Rank'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 13, 15, 16, 17, 18, 19, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,  0])

In [218]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     int64
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     int64
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     float64
dtypes: float64(9), int64(2), object(2)
memory usage: 10.2+ KB

In [ ]:
# 6. Make sure that except for ‘Name of Lending Institution’ 
#   and ‘HQ State, ’ the rest of the columns must be in Int or
#   Float Format.

In [219]:
lend_bkp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 1 to 93
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name of Lending Institution  93 non-null     object
 1   HQ State                     93 non-null     object
 2   Rank                         93 non-null     int64
 3   TA Ratio1                    93 non-null     float64
 4   TBL Ratio1                   93 non-null     float64
 5   Amount ($1,000)              93 non-null     float64
 6   Number                       93 non-null     float64
 7   Lender Asset Size            93 non-null     int64
 8   Amount ($1,000).1            93 non-null     float64
 9   Number .1                    93 non-null     float64
 10  Amount ($1,000).2            93 non-null     float64
 11  Number .2                    93 non-null     float64
 12  CC Amount/TA1                93 non-null     float64
dtypes: float64(9), int64(2), object(2)
memory usage: 10.2+ KB

In [ ]:
# 7. Finally, Save the cleansed file into CSV Format

In [221]:
lend_bkp.to_csv('/Users/shans/Downloads/Lending_cleansed.csv',index=False)

In [222]:
lend_bkp.to_csv('/Users/shans/Downloads/Lending_cleansed1.csv')